/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PruebaArchivoBinario;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author samuelborjas
 */
public class NewJFrame extends javax.swing.JFrame {
    static Archivo a = new Archivo();
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdAgregar = new javax.swing.JButton();
        cmdIngresar = new javax.swing.JButton();
        cmdCambiar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtPuntos = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        print = new javax.swing.JButton();
        newPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdAgregar.setText("Agregar");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });

        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });

        cmdCambiar.setText("Cambiar pass");
        cmdCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCambiarActionPerformed(evt);
            }
        });

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(txtPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(cmdAgregar)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmdCambiar)
                                .addGap(44, 44, 44)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cmdBorrar))
                            .addComponent(cmdIngresar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(print))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAgregar)
                    .addComponent(cmdIngresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCambiar)
                    .addComponent(cmdBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(print)
                .addGap(29, 29, 29)
                .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed
        String name = txtNombre.getText();
        String pass = String.valueOf(txtPass.getPassword());
        int points = Integer.parseInt(txtPuntos.getText());
        boolean activado = true;
     
        if(pass.length() > 5){
            JOptionPane.showMessageDialog (null, "Contraseña muy larga; debe de ser exactamente de 5 caracteres.", "Agregar Usuario", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(pass.length() < 5){
            JOptionPane.showMessageDialog (null, "Contraseña muy corta; debe de ser exactamente de 5 caracteres.", "Agregar Usuario", JOptionPane.INFORMATION_MESSAGE);
            return;    
        }
        try {
            if(a.AgregarPlayer(name, pass, points,activado)){
                    JOptionPane.showMessageDialog (null, "Usuario Agregado Exitosamente!!", "Agregar Usuario", JOptionPane.INFORMATION_MESSAGE);
            }else{
               JOptionPane.showMessageDialog (null, "Usuario repetido. Ingrese un usario valido", "Agregar Usuario", JOptionPane.INFORMATION_MESSAGE);
            }
                
        } catch (IOException e) {
            JOptionPane.showMessageDialog (null, ""+e, "Agregar Usuario", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void cmdCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCambiarActionPerformed
        String nombre = txtNombre.getText();
        String passv = String.valueOf(txtPass.getPassword());
        String passn = String.valueOf(newPass.getPassword());
        
        try {
            if(a.cambiarPass(nombre, passv, passn)){
                JOptionPane.showMessageDialog (null, "Contraseña cambiada exitosamente", "Cambiar Contraseña", JOptionPane.INFORMATION_MESSAGE); 
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog (null, ""+ex, "Cambiar Contraseña", JOptionPane.INFORMATION_MESSAGE); 
        }
      
    }//GEN-LAST:event_cmdCambiarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        String name = txtNombre.getText();
   
        int reply = JOptionPane.showConfirmDialog(null, "Esta seguro que quiere borrar el usuario?", "Borrar Usuario", JOptionPane.YES_NO_OPTION);        
            
        if (reply == JOptionPane.YES_OPTION) {
            try {
                if(a.borrarUsuario(name)){
                  JOptionPane.showMessageDialog (null, "Usuario Eliminado", "Borrar Usuario", JOptionPane.INFORMATION_MESSAGE);  
                }else{
                    JOptionPane.showMessageDialog (null, "No se elimino nada", "Borrar Usuario", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog (null, ""+e, "Borrar Usuario", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            a.imprimirDatos();
        } catch (IOException ex) {
            System.out.println(""+ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
        String name = txtNombre.getText();
        String pass = String.valueOf(txtPass.getPassword());
        try {
            if(a.Ingresar(name, pass)){
                JOptionPane.showMessageDialog (null, "Se ha autenticado correctamente", "Ingresar", JOptionPane.INFORMATION_MESSAGE);
            }else{
              JOptionPane.showMessageDialog (null, "Usuario no existe o contraseña incorrecta", "Ingresar", JOptionPane.INFORMATION_MESSAGE);  
              
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog (null, ""+ex, "Ingresar", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCambiar;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JButton print;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPuntos;
    // End of variables declaration//GEN-END:variables
}
